export default {
    logo: require('@/assets/logo.png'),
    fly: require('@/assets/fly.png'),
    bird: require('@/assets/bird.png'),
    wechat: require('@/assets/wechat.png'),


    telegram1: require('@/assets/concat/telegram1.png'),
    twitter1: require('@/assets/concat/twitter1.png'),
    medium1: require('@/assets/concat/medium1.png'),
    github1: require('@/assets/concat/github1.png'),


    banner1: require('@/assets/banner1.png'),
    igobg: require('@/assets/igobg.png'),
    eth: require('@/assets/eth.e1bcaa36-1.svg'),
    dnftLogo: require('@/assets/dnftLogo-1.svg'),
    example_nft: require('@/assets/nft.jpg'),
    art1: require('@/assets/art1.jpg'),
    art2: require('@/assets/art2.jpg'),
    art3: require('@/assets/art3.jpg'),
    assets1: require('@/assets/assets1.svg'),
    metawallet: require('@/assets/metamask-fox.svg'),
    pro1: require('@/assets/pro1.png'),
    home: require('@/assets/home.png'),
    assets: require('@/assets/assets.png'),
    nftMining: require('@/assets/nftMining.png'),
    nftNav: require('@/assets/nftNav.png'),
    leaderboard: require('@/assets/leaderboard.png'),
    art: require('@/assets/art.png'),
    data: require('@/assets/data.png'),
    game: require('@/assets/game.png'),
    igo: require('@/assets/igo.png'),
    trade: require('@/assets/trade.png'),


    home1: require('@/assets/aside/home1.png'),
    assets1: require('@/assets/aside/assets1.png'),
    nftMining1: require('@/assets/aside/nftMining1.png'),
    nftNav1: require('@/assets/aside/nftNav1.png'),
    leaderboard1: require('@/assets/aside/leaderboard1.png'),
    art1: require('@/assets/aside/art1.png'),
    data1: require('@/assets/aside/data1.png'),
    game1: require('@/assets/aside/game1.png'),
    igo1: require('@/assets/aside/igo1.png'),
    trade1: require('@/assets/aside/trade1.png'),

    1: require('@/assets/market/1.gif'),
    2: require('@/assets/market/2.gif'),
    3: require('@/assets/market/3.gif'),
    4: require('@/assets/market/4.gif'),
    5: require('@/assets/market/5.png'),
    6: require('@/assets/market/6.png'),
    7: require('@/assets/market/7.gif'),
    8: require('@/assets/market/8.png'),
    9: require('@/assets/arts/1.jpg'),
    10: require('@/assets/arts/2.jpg'),
    11: require('@/assets/arts/3.jpg'),
    12: require('@/assets/arts/4.gif'),
    13: require('@/assets/arts/5.png'),
    14: require('@/assets/arts/6.gif'),
    15: require('@/assets/arts/7.gif'),
    16: require('@/assets/arts/8.gif'),

    tianjia: require('@/assets/tianjia.png'),

    game_banner:require('@/assets/games/banner.png'),
    _game1:require('@/assets/games/game1.png'),
    game2:require('@/assets/games/game2.png'),
    game3:require('@/assets/games/game3.png'),
    game4:require('@/assets/games/game4.png'),
    game5:require('@/assets/games/game5.png'),
    game6:require('@/assets/games/game6.png'),
    game7:require('@/assets/games/game7.png'),
    game8:require('@/assets/games/game8.png'),
    game9:require('@/assets/games/game9.png'),
    game10:require('@/assets/games/game10.png'),
    game_banner1:require('@/assets/games/game_banner1.png'),
    game_banner1_right:require('@/assets/games/game_banner1_right.png'),


}