import { Images } from '@/constants'
const markets = [
    {
        img: Images[1],
        id: 1,
        title: 'CryptoEff #3',
        price_cny: '0.1',
        price: '0.7',
        notice: 'crypto Chicken Coop...',
        state: 1,
        des: 'Assemble your crypto Chicken Coop... Buy and Sell Crypto Chickens, Crypto Cocks, Crypto Eggs, Crypto Chicks and more... Collect the whole chicken family... They must be together!',
    },
    {
        img: Images[2],
        id: 2,
        title: 'Allsion Lee',
        price_cny: '18.23',
        price: '2.988',
        notice: 'hashmasks',
        state: 1,
        des: "Hashmask names can change at any time. Immediately before purchasing a Hashmask, enter the Hashmask's token ID into the tokenNameByIndex function on a site like Etherscan to verify that the blockchain indicates that the Hashmask you're purchasing has the name you expect."
    },
    {
        img: Images[3],
        id: 3,
        title: 'Rainforest',
        price_cny: '222.61',
        price: '0.13',
        notice: 'supposed to be a revolution',
        state: 2,
        des: 'The average cost to preserve an acre of the rainforest from logging, palm oil production, and mining is only $2. The average carbon storage of an acre of rainforest is 147.5 metric tonnes.',       des: 'Assemble your crypto Chicken Coop... Buy and Sell Crypto Chickens, Crypto Cocks, Crypto Eggs, Crypto Chicks and more... Collect the whole chicken family... They must be together!',
    },
    {
        img: Images[4],
        id: 4,
        title: 'rainforest',
        price_cny: '32',
        price: '11',
        notice: 'the Rainforest Trust',
        state: 3,
        des: 'All profits (after gas and marketplace fees) from the original sale of each Millennium Cat Phase One token will be donated to the Rainforest Trust',
    },
    {
        img: Images[5],
        id: 5,
        title: 'Wounded #1',
        price_cny: '134',
        price: '32',
        notice: 'Cryptohamsters wounded',
        state: 3,
        des: 'The average cost to preserve an acre of the rainforest from logging, palm oil production, and mining is only $2. The average carbon storage of an acre of rainforest is 147.5 metric tonnes.'
    },
    {
        img: Images[6],
        id: 6,
        title: 'MEDIUM HOME',
        price_cny: '0.01',
        price: '0.07',
        notice: 'Grandpa Smurf plus',
        des: 'Premium Land plus Grandpa Smurf plus 3 Smurfs NFTs',
    },
    {
        img: Images[7],
        id: 7,
        title: 'CryptoBeer 23#',
        price_cny: '12.31',
        price: '2.98',
        notice: 'Premium land with all Smurfs NFTs',
        state: 4,
        des: 'This is a very expensive VIP Crypto Beer! Limited edition! A total of 2 cans of such beer were produced!',
    },
    {
        img: Images[8],
        id: 8,
        title: 'Cryptohamsters Vladimir Putin',
        price_cny: '150.6',
        price: '20.1',
        notice: ' Worldwide tattoo challenge Cryptohamsters',
        state: 1,
        des: 'Each hamster symbolizes a member of the cryptosphere. Someone holds a crypt, while someone is afraid and sells at the slightest correction. We are all different, but in some ways we are surprisingly similar',
    },
]
export default markets;